# Generated by Django 4.2 on 2023-04-25 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('idauthor', models.AutoField(db_column='idAuthor', primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'author',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('iddiscount', models.AutoField(db_column='idDiscount', primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'discount',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('idformat', models.IntegerField(db_column='idFormat', primary_key=True, serialize=False)),
                ('format', models.CharField(max_length=110)),
            ],
            options={
                'db_table': 'format',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('idgenre', models.AutoField(db_column='idGenre', primary_key=True, serialize=False)),
                ('genre', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'genre',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('idlanguage', models.AutoField(db_column='idLanguage', primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'language',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('idbook', models.AutoField(db_column='idBook', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('average_rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('description', models.TextField()),
                ('isbn', models.CharField(max_length=13)),
                ('num_pages', models.IntegerField(blank=True, null=True)),
                ('publication_year', models.IntegerField()),
                ('cover_img', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('ratings_count', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('edition_information', models.CharField(max_length=250)),
                ('is_ebook', models.IntegerField(blank=True, null=True)),
                ('publisher', models.CharField(max_length=250)),
                ('discount_iddiscount', models.ForeignKey(blank=True, db_column='Discount_idDiscount', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.discount')),
                ('format_idformat', models.ForeignKey(db_column='Format_idFormat', on_delete=django.db.models.deletion.RESTRICT, to='products.format')),
                ('language_idlanguage', models.ForeignKey(db_column='Language_idLanguage', on_delete=django.db.models.deletion.RESTRICT, to='products.language')),
            ],
            options={
                'db_table': 'book',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Bookhasgenres',
            fields=[
                ('book_idbook', models.OneToOneField(db_column='Book_idBook', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='products.book')),
                ('genre_idgenre', models.ForeignKey(db_column='Genre_idGenre', on_delete=django.db.models.deletion.CASCADE, to='products.genre')),
            ],
            options={
                'db_table': 'bookhasgenres',
                'managed': True,
                'unique_together': {('book_idbook', 'genre_idgenre')},
            },
        ),
        migrations.CreateModel(
            name='Bookhasauthor',
            fields=[
                ('author_idauthor', models.OneToOneField(db_column='Author_idAuthor', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='products.author')),
                ('book_idbook', models.ForeignKey(db_column='Book_idBook', on_delete=django.db.models.deletion.CASCADE, to='products.book')),
            ],
            options={
                'db_table': 'bookhasauthor',
                'managed': True,
                'unique_together': {('author_idauthor', 'book_idbook')},
            },
        ),
    ]
