# Generated by Django 4.2 on 2023-05-07 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_iduser',
            field=models.ForeignKey(db_column='User_idUser', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='branch',
            name='deliverycompany_iddeliverycompany',
            field=models.ForeignKey(db_column='DeliveryCompany_idDeliveryCompany', on_delete=django.db.models.deletion.RESTRICT, to='orders.deliverycompany'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='book_idbook',
            field=models.ForeignKey(db_column='Book_idBook', on_delete=django.db.models.deletion.CASCADE, to='products.book'),
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order_idorder', 'book_idbook')},
        ),
    ]
